name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
    BuildNumber: $(date +%s)
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump Github Environment Variables
      id: buildnumber
      run: |
        echo 'HOME':${{ env.HOME}}
        echo 'GITHUB_RUN_ID':${{ env.GITHUB_RUN_ID}}
        echo 'GITHUB_RUN_NUMBER':${{ env.GITHUB_RUN_NUMBER}}
        echo "::set-output name=build_number::$(date +%s)"

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Build Image'
      run: |
        echo 'BuildNumber':${{ steps.buildnumber.outputs.build_number }}
        cd src
        docker build . --file ./Build-Dockerfile     --tag fluffybunny/oauth2tokenmanagementbuild 
        docker build . --file ./App-Dockerfile       --tag fluffybunny/oauth2tokenmanagementapp:${{ steps.buildnumber.outputs.build_number }}
        docker tag fluffybunny/oauth2tokenmanagementapp:${{ steps.buildnumber.outputs.build_number }}    fluffybunny/oauth2tokenmanagementapp:latest

 

 